
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package c0;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 8;
  public static final int IDENT = 28;
  public static final int SEMICOLON = 22;
  public static final int ELSE = 16;
  public static final int PLUS = 2;
  public static final int INT = 27;
  public static final int RPAREN = 18;
  public static final int OR = 7;
  public static final int EQUAL = 9;
  public static final int NOTEQUAL = 10;
  public static final int WHILE = 15;
  public static final int IF = 14;
  public static final int LBRACKET = 19;
  public static final int LPAREN = 17;
  public static final int RBRACKET = 20;
  public static final int QUOTE = 21;
  public static final int STRING = 29;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int MAIN = 23;
  public static final int BREAK = 26;
  public static final int DIV = 5;
  public static final int PUTW = 24;
  public static final int MINOR = 11;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int PUTS = 25;
  public static final int ASSIGN = 6;
  public static final int BOOL = 13;
  public static final int MUL = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "ASSIGN",
  "OR",
  "AND",
  "EQUAL",
  "NOTEQUAL",
  "MINOR",
  "MAYOR",
  "BOOL",
  "IF",
  "WHILE",
  "ELSE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "QUOTE",
  "SEMICOLON",
  "MAIN",
  "PUTW",
  "PUTS",
  "BREAK",
  "INT",
  "IDENT",
  "STRING"
  };
}

